// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FantasyDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250322204355_NewLayoutWithFK")]
    partial class NewLayoutWithFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FantasyDB.Models.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Effects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("SnapshotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Artifact");
                });

            modelBuilder.Entity("FantasyDB.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysPerWeek")
                        .HasColumnType("int");

                    b.Property<int>("DaysPerYear")
                        .HasColumnType("int");

                    b.Property<string>("Months")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthsPerYear")
                        .HasColumnType("int");

                    b.Property<string>("Weekdays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Calendar");
                });

            modelBuilder.Entity("FantasyDB.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BirthDay")
                        .HasColumnType("int");

                    b.Property<string>("BirthMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("Build")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefiningFeatures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eyes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FactionId")
                        .HasColumnType("int");

                    b.Property<string>("Fear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hair")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HeightCm")
                        .HasColumnType("int");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Magic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Misbelief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Personality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("SocialStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weakness")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FactionId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LocationId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("FantasyDB.Models.CharacterRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Character1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Character2Id")
                        .HasColumnType("int");

                    b.Property<string>("RelationshipDynamic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SnapshotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Character1Id");

                    b.HasIndex("Character2Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("CharacterRelationship");
                });

            modelBuilder.Entity("FantasyDB.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Crown")
                        .HasColumnType("int");

                    b.Property<int?>("Penny")
                        .HasColumnType("int");

                    b.Property<int?>("Shilling")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("FantasyDB.Models.Era", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("MagicStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MagicSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<int?>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Era");
                });

            modelBuilder.Entity("FantasyDB.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("FantasyDB.Models.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FounderId")
                        .HasColumnType("int");

                    b.Property<int?>("FoundingYear")
                        .HasColumnType("int");

                    b.Property<int?>("HQLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("LeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Magic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SnapshotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FounderId");

                    b.HasIndex("HQLocationId");

                    b.HasIndex("LeaderId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Faction");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+LocationEvent", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("LocationEvent");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+LanguageLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("LanguageLocation");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+LocationLocation", b =>
                {
                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("ChildLocationId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "ChildLocationId");

                    b.HasIndex("ChildLocationId");

                    b.ToTable("LocationLocation");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotArtifact", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<int>("ArtifactId")
                        .HasColumnType("int");

                    b.HasKey("SnapshotId", "ArtifactId");

                    b.HasIndex("ArtifactId");

                    b.ToTable("SnapshotArtifact");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotCharacter", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.HasKey("SnapshotId", "CharacterId");

                    b.HasIndex("CharacterId");

                    b.ToTable("SnapshotCharacter");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotCharacterRelationship", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterRelationshipId")
                        .HasColumnType("int");

                    b.HasKey("SnapshotId", "CharacterRelationshipId");

                    b.HasIndex("CharacterRelationshipId");

                    b.ToTable("SnapshotCharacterRelationship");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotEra", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<int>("EraId")
                        .HasColumnType("int");

                    b.HasKey("SnapshotId", "EraId");

                    b.HasIndex("EraId");

                    b.ToTable("SnapshotEra");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotEvent", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.HasKey("SnapshotId", "EventId");

                    b.HasIndex("EventId");

                    b.ToTable("SnapshotEvent");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotFaction", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<int>("FactionId")
                        .HasColumnType("int");

                    b.HasKey("SnapshotId", "FactionId");

                    b.HasIndex("FactionId");

                    b.ToTable("SnapshotFaction");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotLocation", b =>
                {
                    b.Property<int>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("SnapshotId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("SnapshotLocation");
                });

            modelBuilder.Entity("FantasyDB.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("FantasyDB.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Biome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChildLocationsId")
                        .HasColumnType("int");

                    b.Property<string>("Cultures")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DivineMagicians")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Politics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SnapshotId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalPopulation")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WildMagicians")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("ParentLocationId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("FantasyDB.Models.PriceExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exclusivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PriceExample");
                });

            modelBuilder.Entity("FantasyDB.Models.River", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepthMeters")
                        .HasColumnType("int");

                    b.Property<int?>("DestinationLocationId")
                        .HasColumnType("int");

                    b.Property<string>("FlowDirection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("WidthMeters")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("SourceLocationId");

                    b.ToTable("River");
                });

            modelBuilder.Entity("FantasyDB.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FromId")
                        .HasColumnType("int");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToId")
                        .HasColumnType("int");

                    b.Property<string>("TravelTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FromId");

                    b.HasIndex("ToId");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("FantasyDB.Models.Snapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Act")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chapter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SnapshotName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.Artifact", b =>
                {
                    b.HasOne("FantasyDB.Models.Character", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId");

                    b.Navigation("Owner");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.Character", b =>
                {
                    b.HasOne("FantasyDB.Models.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId");

                    b.HasOne("FantasyDB.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.HasOne("FantasyDB.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId");

                    b.Navigation("Faction");

                    b.Navigation("Language");

                    b.Navigation("Location");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.CharacterRelationship", b =>
                {
                    b.HasOne("FantasyDB.Models.Character", "Character1")
                        .WithMany()
                        .HasForeignKey("Character1Id");

                    b.HasOne("FantasyDB.Models.Character", "Character2")
                        .WithMany()
                        .HasForeignKey("Character2Id");

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId");

                    b.Navigation("Character1");

                    b.Navigation("Character2");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.Era", b =>
                {
                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.Event", b =>
                {
                    b.HasOne("FantasyDB.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId");

                    b.Navigation("Location");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.Faction", b =>
                {
                    b.HasOne("FantasyDB.Models.Character", "Founder")
                        .WithMany()
                        .HasForeignKey("FounderId");

                    b.HasOne("FantasyDB.Models.Location", "HQLocation")
                        .WithMany()
                        .HasForeignKey("HQLocationId");

                    b.HasOne("FantasyDB.Models.Character", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId");

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId");

                    b.Navigation("Founder");

                    b.Navigation("HQLocation");

                    b.Navigation("Leader");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+LocationEvent", b =>
                {
                    b.HasOne("FantasyDB.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyDB.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+LanguageLocation", b =>
                {
                    b.HasOne("FantasyDB.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyDB.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+LocationLocation", b =>
                {
                    b.HasOne("FantasyDB.Models.Location", "ChildLocation")
                        .WithMany()
                        .HasForeignKey("ChildLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyDB.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildLocation");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotArtifact", b =>
                {
                    b.HasOne("FantasyDB.Models.Artifact", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotCharacter", b =>
                {
                    b.HasOne("FantasyDB.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotCharacterRelationship", b =>
                {
                    b.HasOne("FantasyDB.Models.CharacterRelationship", "CharacterRelationship")
                        .WithMany()
                        .HasForeignKey("CharacterRelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterRelationship");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotEra", b =>
                {
                    b.HasOne("FantasyDB.Models.Era", "Era")
                        .WithMany()
                        .HasForeignKey("EraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Era");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotEvent", b =>
                {
                    b.HasOne("FantasyDB.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotFaction", b =>
                {
                    b.HasOne("FantasyDB.Models.Faction", "Faction")
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.JunctionClasses+SnapshotLocation", b =>
                {
                    b.HasOne("FantasyDB.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.Language", b =>
                {
                    b.HasOne("FantasyDB.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FantasyDB.Models.Location", b =>
                {
                    b.HasOne("FantasyDB.Models.Event", "Events")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("FantasyDB.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.HasOne("FantasyDB.Models.Location", "ParentLocation")
                        .WithMany()
                        .HasForeignKey("ParentLocationId");

                    b.HasOne("FantasyDB.Models.Snapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId");

                    b.Navigation("Events");

                    b.Navigation("Language");

                    b.Navigation("ParentLocation");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("FantasyDB.Models.River", b =>
                {
                    b.HasOne("FantasyDB.Models.Location", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId");

                    b.HasOne("FantasyDB.Models.Location", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId");

                    b.Navigation("DestinationLocation");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("FantasyDB.Models.Route", b =>
                {
                    b.HasOne("FantasyDB.Models.Location", "From")
                        .WithMany()
                        .HasForeignKey("FromId");

                    b.HasOne("FantasyDB.Models.Location", "To")
                        .WithMany()
                        .HasForeignKey("ToId");

                    b.Navigation("From");

                    b.Navigation("To");
                });
#pragma warning restore 612, 618
        }
    }
}
